### ISSUE TITLE
Failed to load the simple-drag-drop-text package

### ISSUE THREAD

**Issue by clemorphy** [geoffthibeau/simple-drag-drop-text#8]
[Enter steps to reproduce below:]
1. Launch Atom

**Atom Version**: 1.0.15
**System**: Windows 8.1
**Thrown From**: [simple-drag-drop-text](https://github.com/mark-hahn/simple-drag-drop-text) package, v0.3.0
### Stack Trace

Failed to load the simple-drag-drop-text package

```
At Cannot find module 'sub-atom'

Error: Cannot find module 'sub-atom'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Clément\.atom\packages\simple-drag-drop-text\lib\simple-drag-drop-text.coffee:7:11)
  at Object.<anonymous> (C:\Users\Clément\.atom\packages\simple-drag-drop-text\lib\simple-drag-drop-text.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:761:34)
  at C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:192:28
  at Package.module.exports.Package.measure (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.load (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package-manager.js:141:19)
  at HTMLButtonElement.<anonymous> (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\Clément\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
  2x -0:18.2.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -0:16.2.0 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-atom-api",
      "autocomplete-snippets"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.11
minimap, v4.13.3
php-twig, v4.0.0
simple-drag-drop-text, v0.3.0

# Dev
No dev packages
```

**Comment by clemorphy** [comment]
Same issue with other packages here : https://github.com/atom/atom/issues/8891

**Comment by geoffthibeau** [comment]
If the Atom team didn't resolve it in atom/atom#8891, the recent release has removed sub-atom as a dependency: 4056c70d0f16407db17bc04d60bd0512dfd454a8.
